---
title: "Classification Tree Attempt"
author: "Julianna Alvord"
date: "12/9/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(knitr)
library(dplyr)
library(class)
library(mosaic)
library(tidyr)
library(maps)
library(ggplot2)
library(datasets)
library(broom)
library(modelr)
library(purrr)
library(tidyr)
library(boot)
library(tree)
library(gbm)
library(caret)
library(ROCR)

accident <- read.csv("accident.csv")
```

#Cleaning the Dataset
```{r, results = "hide", message = FALSE}
accident1 <- accident %>%
  #creating percent_killed outcome variable
  mutate(total_persons = (PERNOTMVIT + PERMVIT),
         percent_killed = (FATALS/total_persons)) %>%
  #selecting columns we want to include in the models
  select(c(STATE, MONTH, DAY_WEEK, HOUR, MAN_COLL, TYP_INT, WRK_ZONE, 
           LGT_COND, WEATHER1, DRUNK_DR, percent_killed, total_persons))

med_percent_fatalities <- median(accident1$percent_killed)

accident1 <- accident1 %>%
  mutate(fatal_med = as.factor(ifelse(percent_killed > med_percent_fatalities, "above", "below")))
  #filter(!(total_persons == 1 & percent_killed == 1))

#state
states <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", 
            "Connecticut", "Delaware", "District of Columbia", "Florida", 
            "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", 
            "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", 
            "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
            "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", 
            "New York","North Carolina", "North Dakota", "Ohio", "Oklahoma", 
            "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island",
            "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", 
            "Vermont", "Virginia", "Virgin Islands", 
            "Washington", "West Virginia", "Wisconsin", "Wyoming")

accident1 <- accident1 %>%
  mutate(states_cat = factor(STATE, levels = c(1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 
                                               13, 15, 16, 17, 18, 19, 20,
                                               21, 22, 23, 24, 25, 26, 27, 28, 
                                               29, 30, 31, 32, 33, 34, 35,
                                               36, 37, 38, 39, 40, 41, 42, 43, 
                                               44, 45, 46, 47, 48, 49, 50, 51,
                                               52, 53, 54, 55, 56), labels = states)) %>%
  select(-STATE)

#month
months <- c("January", "February", "March", "April", "May", "June", 
            "July", "August", "September", "October",
            "November", "December")

accident1 <- accident1 %>%
  mutate(months_cat = factor(MONTH, levels = c(1:12), labels = months)) %>%
  select(-MONTH)

#day_week
days <- c("Sunday", "Monday", "Tuesday", "Wednesday", 
          "Thursday", "Friday", "Saturday")

accident1 <- accident1 %>%
  mutate(day_week_cat = factor(DAY_WEEK, levels = c(1:7), labels = days)) %>%
  select(-DAY_WEEK)

#hour
accident1 <- accident1 %>%
  filter(!HOUR == 99) %>%
  mutate(hour_cat = as.factor(HOUR)) %>%
  select(-HOUR)

#manner of collision
collision <- c("not collision", "front-to-rear", "front-to-front", 
               "angle", "sideswipe-same", "sideswipe-different",
               "read-to-side", "rear-to-rear", "other")

accident1 <- accident1 %>%
  filter(!MAN_COLL %in% c(98, 99)) %>%
  mutate(man_coll_cat = factor(MAN_COLL, levels = c(0,1,2,6,7,8,9
                                                    ,10,11), labels = collision)) %>%
  select(-MAN_COLL)

#type of intersection
intersection <- c("not intersection", "four-way", "t-intersection", 
                  "y-intersection", "traffic circle", "roundabout",
                  "five point+")

accident1 <- accident1 %>%
  filter(!TYP_INT %in% c(10, 98, 99)) %>%
  mutate(type_int_cat = factor(TYP_INT, levels = c(1:7), labels = intersection)) %>%
  select(-TYP_INT)

#work zone
accident1 <- accident1 %>%
  mutate(work_zone_bin = ifelse(WRK_ZONE == 0, 0, 1)) %>%
  select(-WRK_ZONE)

#light condition
light <- c("daylight", "dark-not lighted", "dark-lighted", 
           "dawn", "dusk", "dark-unknown", "other")

accident1 <- accident1 %>%
  filter(!LGT_COND %in% c(8, 9)) %>%
  mutate(lgt_cond_cat = factor(LGT_COND, levels = c(1:7), labels = light)) %>%
  select(-LGT_COND)

#weather
weather <- c("none", "clear", "rain", "sleet", "snow", "fog", 
             "crosswinds", "blowing sand", "other", "cloudy", 
             "blowing snow")

accident1 <- accident1 %>%
  filter(!WEATHER1 %in% c(98, 99)) %>%
  mutate(weather_cat = factor(WEATHER1, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 
                                                   10, 11, 12), labels = weather)) %>%
  select(-WEATHER1)

#drunk_driver
accident1 <- accident1 %>%
  mutate(drunk_dr_bin = ifelse(DRUNK_DR == 0, 0, 1)) %>%
  select(-DRUNK_DR)
```

#test and training data
```{r}
#number above or below in full dataset
table(accident1$fatal_med)
9839/(9839+21615)
#31.2% were above the median
#68.8% were at or below the median


accident1 <- accident1 %>%
  select(-c(total_persons, percent_killed))

set.seed(1)

train <- accident1 %>%
  sample_frac(0.2)

#number above or below in train
table(train$fatal_med)
1981/(1981+4310)
#31.4%

test <- accident1 %>%
  setdiff(train)

#number above or below in test
table(test$fatal_med)
7675/(7675+16921)
#31.2%

```

#running classification tree
```{r}
tree_fatalities <- tree(fatal_med ~ . -states_cat, train)

summary(tree_fatalities)

plot(tree_fatalities)
text(tree_fatalities, pretty = 0)
```

#How did it perform on test data?
```{r}
tree_pred <- predict(tree_fatalities, test, type = "class")


table(tree_pred, test$fatal_med)

((5427+13173)/24557)

#much higher at 75%
```

#running a cross-validation
#classification error rate instead of deviance (default)
```{r}
set.seed(3)
cv_fatalities = cv.tree(tree_fatalities, FUN = prune.misclass)
```

#plotting the cross-validation results
```{r}
plot(cv_fatalities$size, cv_fatalities$dev, type = "b")

prune_fatalities <- prune.misclass(tree_fatalities, best = 2)
plot(prune_fatalities)
text(prune_fatalities, pretty = 0)

tree_pred <- predict(prune_fatalities, test, type = "class")
table(tree_pred, test$fatal_med)

(15315+2973)/24596
#slightly lower prediction accuracy
#more interpretable tree
```





#running with a different package
```{r}
dummies <- dummyVars(~ ., data = accident1)
accident2 <- as.data.frame(predict(dummies, newdata = accident1))


response <- accident1$fatal_med

accident2 <- bind_cols(accident2, fatal_med = response)

set.seed(1)

train <- accident2 %>%
  sample_frac(0.2)

test <- accident2 %>%
  setdiff(train)

train <- train %>%
  select(-c(fatal_med.above, fatal_med.below))

test <- test %>%
  select(-c(fatal_med.above, fatal_med.below))

tree_fatalities <- rpart(fatal_med~ ., train)

tree_fatalities

# can we use this?

tree_pred <- predict(tree_fatalities, test, type = "class")

table(tree_pred, test$fatal_med)

((5317+13267)/24596)

rpart.plot(tree_fatalities)
```

#baseline
```{r}
table(test$fatal_med)

#predicting all as below
7675/(7675+16921)
#31% baseline accuracy

#predicting all as above
16921/(7675+16921)
#69% accuracy
```





#trying a boosting tree
```{r}
set.seed(1)

train <- accident1 %>%
  sample_frac(0.2)

test <- accident1 %>%
  setdiff(train)

train <- train %>%
  mutate(med_fatal = ifelse(fatal_med == "above", 1, 0)) %>%
  select(-fatal_med)

test <- test %>%
  mutate(med_fatal = ifelse(fatal_med == "above", 1, 0)) %>%
  select(-fatal_med)

boost_fatalities <- gbm(med_fatal~.,
                    data = train,
                    distribution = "bernoulli",
                    n.trees = 5000,
                    shrinkage = 0.01,
                    interaction.depth = 4)

summary(boost_fatalities)

plot(boost_fatalities, i = "states_cat")
plot(boost_fatalities, i = "man_coll_cat")
plot(boost_fatalities, i = "drunk_dr_bin")
plot(boost_fatalities, i = "hour_cat")
```

```{r}
boost_estimate <- predict(boost_fatalities,
                         newdata = test,
                         n.trees = 5000)

boost_class<-ifelse(boost_estimate<=0.5,0,1)

table(boost_class,test$med_fatal)

(15181+2786)/24596

#lower prediction accuracy

n.trees = seq(from=100 ,to=5000, by=100) #no of trees-a vector of 100 values 

#Generating a Prediction matrix for each Tree
predmat = predict(boost_fatalities, newdata = test, n.trees = n.trees)
```

