---
title: "Results Stage"
author: "Julianna Alvord, Tony Zhang, Kara VanAllen, Aurora Lopez, Vivian Wang"
date: "11/28/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(knitr)
library(dplyr)
library(class)
library(mosaic)
library(tidyr)
library(maps)
library(ggplot2)
library(datasets)
library(broom)
library(modelr)
library(purrr)
library(tidyr)
library(boot)

accident <- read.csv("accident.csv")
```

#Cleaning the Dataset
```{r, results = "hide", message = FALSE}
accident1 <- accident %>%
  #creating percent_killed outcome variable
  mutate(total_persons = (PERNOTMVIT + PERMVIT),
         percent_killed = (FATALS/total_persons)) %>%
  #selecting columns we want to include in the models
  select(c(STATE, MONTH, DAY_WEEK, HOUR, MAN_COLL, TYP_INT, WRK_ZONE, 
           LGT_COND, WEATHER1, DRUNK_DR, percent_killed, total_persons))

med_percent_fatalities <- median(accident1$percent_killed)

accident1 <- accident1 %>%
  mutate(above_fatal_med = as.factor(ifelse(percent_killed >= med_percent_fatalities, "above", "below")))

#state
states <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", 
            "Connecticut", "Delaware", "District of Columbia", "Florida", 
            "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", 
            "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", 
            "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", 
            "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", 
            "New York","North Carolina", "North Dakota", "Ohio", "Oklahoma", 
            "Oregon", "Pennsylvania", "Puerto Rico", "Rhode Island",
            "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", 
            "Vermont", "Virginia", "Virgin Islands", 
            "Washington", "West Virginia", "Wisconsin", "Wyoming")

accident1 <- accident1 %>%
  mutate(states_cat = factor(STATE, levels = c(1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 
                                               13, 15, 16, 17, 18, 19, 20,
                                               21, 22, 23, 24, 25, 26, 27, 28, 
                                               29, 30, 31, 32, 33, 34, 35,
                                               36, 37, 38, 39, 40, 41, 42, 43, 
                                               44, 45, 46, 47, 48, 49, 50, 51,
                                               52, 53, 54, 55, 56), labels = states)) %>%
  select(-STATE)

#month
months <- c("January", "February", "March", "April", "May", "June", 
            "July", "August", "September", "October",
            "November", "December")

accident1 <- accident1 %>%
  mutate(months_cat = factor(MONTH, levels = c(1:12), labels = months)) %>%
  select(-MONTH)

#day_week
days <- c("Sunday", "Monday", "Tuesday", "Wednesday", 
          "Thursday", "Friday", "Saturday")

accident1 <- accident1 %>%
  mutate(day_week_cat = factor(DAY_WEEK, levels = c(1:7), labels = days)) %>%
  select(-DAY_WEEK)

#hour
accident1 <- accident1 %>%
  filter(!HOUR == 99) %>%
  mutate(hour_cat = as.factor(HOUR)) %>%
  select(-HOUR)

#manner of collision
collision <- c("not collision", "front-to-rear", "front-to-front", 
               "angle", "sideswipe-same", "sideswipe-different",
               "read-to-side", "rear-to-rear", "other")

accident1 <- accident1 %>%
  filter(!MAN_COLL %in% c(98, 99)) %>%
  mutate(man_coll_cat = factor(MAN_COLL, levels = c(0,1,2,6,7,8,9
                                                    ,10,11), labels = collision)) %>%
  select(-MAN_COLL)

#type of intersection
intersection <- c("not intersection", "four-way", "t-intersection", 
                  "y-intersection", "traffic circle", "roundabout",
                  "five point+")

accident1 <- accident1 %>%
  filter(!TYP_INT %in% c(10, 98, 99)) %>%
  mutate(type_int_cat = factor(TYP_INT, levels = c(1:7), labels = intersection)) %>%
  select(-TYP_INT)

#work zone
accident1 <- accident1 %>%
  mutate(work_zone_bin = ifelse(WRK_ZONE == 0, 0, 1)) %>%
  select(-WRK_ZONE)

#light condition
light <- c("daylight", "dark-not lighted", "dark-lighted", 
           "dawn", "dusk", "dark-unknown", "other")

accident1 <- accident1 %>%
  filter(!LGT_COND %in% c(8, 9)) %>%
  mutate(lgt_cond_cat = factor(LGT_COND, levels = c(1:7), labels = light)) %>%
  select(-LGT_COND)

#weather
weather <- c("none", "clear", "rain", "sleet", "snow", "fog", 
             "crosswinds", "blowing sand", "other", "cloudy", 
             "blowing snow")

accident1 <- accident1 %>%
  filter(!WEATHER1 %in% c(98, 99)) %>%
  mutate(weather_cat = factor(WEATHER1, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 
                                                   10, 11, 12), labels = weather)) %>%
  select(-WEATHER1)

#drunk_driver
accident1 <- accident1 %>%
  mutate(drunk_dr_bin = ifelse(DRUNK_DR == 0, 0, 1)) %>%
  select(-DRUNK_DR)
```

#Running Cross-Validation and Logistic Regression
```{r, results = "hide", message = FALSE}
accident1 <- accident1 %>%
  #getting rid of the variables used to create y variable
  select(-c(total_persons,percent_killed)) %>%
  #filtering out certain levels of the factors in order to avoid error on predict function
  #should we do bootstrap instead?
  filter(!states_cat %in% c("District of Columbia", "Puerto Rico"),
         !man_coll_cat == "rear-to-rear",
         !lgt_cond_cat == "other",
         !type_int_cat %in% c("traffic circle", "roundabout"),
         !weather_cat == "blowing snow")

for (i in 1:10){
  set.seed(i)
  
  train <- accident1 %>%
    sample_frac(0.2)
  
  test <- accident1 %>%
    setdiff(train)
  
  # Fit a logistic regression model to predict whether or not the fatalities 
  # would be above or below the median fatality rate
  glm_fit <- glm(above_fatal_med~.,
              data = train,
              family = binomial)
  
  # Use the model to predict the response on the test data
  glm_probs <- data.frame(probs = predict(glm_fit,
                                       newdata = test,
                                       type="response"))
    
  # Confusion matrix
  glm_pred <- glm_probs %>%
    mutate(pred = ifelse(probs>.5, "above", "below"))
  
  glm_pred <- cbind(test, glm_pred)
  
  result <- glm_pred %>%
    summarize(score = mean(pred == above_fatal_med))
  
  print(glm_pred %>%
    count(pred, above_fatal_med) %>%
    spread(above_fatal_med, n, fill = 0))
  
  print(result)
}

#to look at the predictors individually
  set.seed(10)
  
  train <- accident1 %>%
    sample_frac(0.2)
  
  test <- accident1 %>%
    setdiff(train)
  
  glm_fit <- glm(above_fatal_med~.,
              data = train,
              family = binomial)
  summary(glm_fit)

# set.seed(1)
# cv_errors <- data.frame(delta1 = 0, delta2 = 0)
# 
# for (i in 1:10){
#   model_log = glm(above_fatal_med~.,
#               data = accident1,
#               family = binomial)
#   
#   cv_errors[i, ] = cv.glm(accident1, model_log, K=10)$delta
# }
# 
# cv_errors
```


